### ISSUE TITLE
Mssqlex.Error odbc_not_started

### ISSUE THREAD

**Issue by katbow** [findmypast-oss/mssql_ecto#15]
### Bug details
When I start my phoenix server locally, I get an error that odbc is not started:

```
[error] Mssqlex.Protocol (#PID<0.3246.0>) failed to connect: ** (Mssqlex.Error) odbc_not_started
```

I tried adding `:mssql_ecto` to applications as specified previously in the README, but had a different error instead:

``` 
[error] Mssqlex.Protocol (#PID<0.723.0>) failed to connect: ** (Mssqlex.Error) [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found Connection to database failed. | ODBC_CODE 01000 | SQL_SERVER_CODE 0
```

I have MSSQL running in Azure which I am trying to connect to. I have been able to connect & query using Node. 

### Steps to Reproduce
I followed the instructions in the README here:
1. Ensured I have ODBC application installed 
2. Installed Microsoft's ODBC driver for macOS Sierra [here](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server)
3. Added `{:mssql_ecto, "~> 0.1"}` and `{:mssqlex, "~> 0.6"}` to my deps.
4. Configured my app as below:
```
config :my_app, MyApp.Repo,
  adapter: MssqlEcto,
  username: "<my_username>",
  password: "<my_password>",
  database: "test",
  hostname: "<my_server>.database.windows.net", 
  pool_size: 10
```

### My environment
* MssqlEcto version: 0.1
* Elixir version: 1.4.0
* Erlang version: 19
* Operating System and version: MacOS Sierra 10.12.5

**Comment by toddharding** [comment]
The default version of Erlang on MacOS does not include Erlang ODBC, could you try to install Erlang via [Kerl](https://github.com/kerl/kerl) and follow kerls instructions to enable Erlang ODBC.

If you are still unable to get ODBC to work on MacOS then a fallback solution could be to run your project in a docker container, this is how I develop elixir projects that connect to SQL Server on MacOS.

**Comment by shdblowers** [comment]
@katbow we would like to support mssql_ecto on MacOS in a more official sense and are willing to provide further assistance in order to achieve that.

Hopefully, the resolution of this ticket will include updating our README.md to include instructions specific to MacOS, if the current instructions are relevant. Any help on that from you or @toddharding would be great, as I don't own a MacBook  😓

**Comment by katbow** [comment]
@toddharding Yes, I was having that issue initially where Erlang ODBC was not included in the version of Erlang I had installed. I managed to get it installed with ODBC. I double checked it was included by running `odbc:module_info().` in the Erlang console. 

@shdblowers thanks, I'll keep at it for a bit & let you know if I find a solution 👍 .

**Comment by shdblowers** [comment]
@katbow it could be that the version of the ODBC driver you've installed doesn't match up with what mssqlex expects. [See this](https://github.com/findmypast-oss/mssqlex/blob/master/lib/mssqlex.ex#L18).

Looking at finding a solution...

**Comment by shdblowers** [comment]
@katbow try adding the last line to your config:

```elixir
config :my_app, MyApp.Repo,
  adapter: MssqlEcto,
  username: "<my_username>",
  password: "<my_password>",
  database: "test",
  hostname: "<my_server>.database.windows.net", 
  pool_size: 10
  odbc_driver: "{ODBC Driver 13.1 for SQL Server}"
```

I'm not sure if that will be the correct name of the ODBC driver you have installed on you MacOS. Not sure how to check at this point.

**Comment by RobStallion** [comment]
@toddharding. I have also tried all of the suggestions to this point but have still been experiencing the same issue. I have also added a Vagrantfile to test things in an linux environment but have still had the same issue. 

I have also tried querying the DB with node running in the linux environment and that worked as expected. That code is in the repo that can be found here: https://github.com/RobStallion/azure-elixir. 

If anything is unclear or you would like any more information please let me know.

**Comment by ssomnoremac** [comment]
I've just been through all the steps the healthlocker people have been through. Same exact path. Installed erlang on iOS with kerl, verified odbc is working, installed microsoft driver. Same dead end. If this is a problem in linux too that's not good.

**Comment by ssomnoremac** [comment]
actually @RobStallion @katbow , I just got it to work. Had your same error but after adding deps to applications 
```
def application do
    [mod: {BlogPhoenix, []},
     applications: [:phoenix, :phoenix_pubsub, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :mssqlex, :mssql_ecto]]
```

and REMOVING
```
-  odbc_driver: "{ODBC Driver 13.1 for SQL Server}"
```
it worked!

**Comment by shdblowers** [comment]
Thanks for doing some debugging @ssomnoremac 

My current thoughts are that the `:mssqlex` app is not getting started when only adding `:mssql_ecto` to the list of dependencies.

I will try and investigate this further...

**Comment by shdblowers** [comment]
I can't replicate this bug on my Linux/Ubuntu environment, but my theory is that adding both `mssql_ecto` and `mssqlex` to the list of deps will fix the bug.

i.e. (with Elixir 1.4)

applications will look like:
```elixir
  def application do
    [mod: {Throwaway.Application, []},
     extra_applications: [:logger, :runtime_tools]]
  end
```
and deps:
```elixir
  defp deps do
    [{:mssql_ecto, "~> 0.1"},
     {:mssqlex, "~> 0.6"},
     ...]
  end
```

Could someone with a Mac please confirm?

**Comment by RobStallion** [comment]
@shdblowers I had both `mssql_ecto` and `mssqlex` in the list of deps as you have said above but I could not get it to work like that on mac or ubuntu. 

Following what @ssomnoremac mentioned is the only way I have ben able to get things working (massive thanks btw to everyone for continuing to look into this and get back to us). Otherwise, I was repeatedly getting the same error mentioned by @katbow when the issue was opened..
`[error] Mssqlex.Protocol (#PID<0.3246.0>) failed to connect: ** (Mssqlex.Error) odbc_not_started`.

I only needed to add mssqlex to the application list to remove the error. Just thought I would mention that incase it helped clear things up

**Comment by RobStallion** [comment]
@shdblowers Also I have this working on mac (to answer your original question 😄)

**Comment by shdblowers** [comment]
I'm glad you've managed to get this working @RobStallion @katbow.

Thanks for your help @ssomnoremac.

I think this issue can be closed once the readme has been updated to reflect how you managed to get things to work.

I had a look over your `mix.exs` file on Health Locker [here](https://github.com/healthlocker/healthlocker/blob/116fc410f2975450a126fc8a3a856d28e1809ee4/mix.exs)

I think the problem is understanding how [application inference](https://elixir-lang.org/blog/2017/01/05/elixir-v1-4-0-released/#application-inference) works with Elixir 1.4

I will update the readme to show how to get it to work both with and without application inference, as I think this will be a common issue in Elixir until application inference becomes the standard in everyone's `mix.exs` files.

I think it would also be useful to add to the readme the steps you took to get it working on MacOS and was looking for help on that front.

**Comment by katbow** [comment]
@ssomnoremac thanks very much! 

@shdblowers Oh I see, thanks for that. That's useful to know as it cleans up the config a lot. @RobStallion and I can update the README with instructions for macOS (probably on the weekend, though). 

Really appreciate the help everyone!

**Comment by ssomnoremac** [comment]
@katbow let me know how it goes. For some reason I'm having issues with my associations. I'm not sure if it's an issue with this library or not, or if it's because my table names are capitalized, or if it's an issue with Absinthe-ecto, or my setup, or what. I'm using an existing Azure db so there's a bit to tackle.

**Comment by ssomnoremac** [comment]
actually solved the association issue, had to be careful with plural fields for that.
